### ISSUE TITLE
About project loom 

### ISSUE THREAD

**Issue by HelloTo4x** [akarnokd/RxJavaFiberInterop#74]
Hi, i am reading your project, but why do you use Project Loom ? Why don't you choose Akka ? Can you tell me the advantage and the disadvantage of Project Loom ?

**Comment by akarnokd** [comment]
Because this is a project about using loom. Also Akka supports Reactive Steams already.

**Comment by HelloTo4x** [comment]
Can you tell me the advantage and the disadvantage of Project Loom ?

**Comment by akarnokd** [comment]
I won't bother. Also stop spamming projects with questions.
